openapi: 3.0.0
info:
  title: API de Gestion des Utilisateurs
  version: 1.0.0
  description: API permettant de créer un compte utilisateur.

paths:
  /api/v1/client/agences:
    get:
      summary: Obtenir la liste des agents
      tags:
        - Clients
      responses:
        "200":
          description: Liste des agents récupérée avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: string
                          description: Détails de l'agent.
                        agence:
                          type: string
                          description: Détails de l'agence.
                  message:
                    type: string
                    example: "Liste des agents récupérée avec succès."
                  status:
                    type: string
                    example: "Valider"
        "500":
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur interne s'est produite."

  /api/v1/client/plafonds:
    get:
      summary: Obtenir les informations de plafond du portefeuille
      tags:
        - Clients
      responses:
        "200":
          description: Informations de plafond récupérées avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      wallet:
                        type: string
                        description: Détails du portefeuille.
                  message:
                    type: string
                    example: "Informations de plafond récupérées avec succès."
                  status:
                    type: string
                    example: "Valider"
        "500":
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur interne s'est produite."

  /api/v1/client/password:
    put:
      summary: Mettre à jour le password du client
      tags:
        - Clients
      requestBody:
        description: Password pour mise à jour.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: Nouveau code du client.
                  example: "123456"
      responses:
        "200":
          description: Code mis à jour avec succès.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        description: Jeton d'authentification après mise à jour du code.
                  message:
                    type: string
                    example: "Code mis à jour avec succès."
                  status:
                    type: string
                    example: "Valider"
        "400":
          description: Requête invalide (données manquantes ou incorrectes).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Les données fournies sont invalides."
        "500":
          description: Erreur interne du serveur.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Une erreur interne s'est produite."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
